/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.store_app.view;

import com.mycompany.store_app.controller.BarangController;
import com.mycompany.store_app.controller.PenjualanController;
import com.mycompany.store_app.controller.UserController;
import com.mycompany.store_app.controller.VoucherController;
import com.mycompany.store_app.model.entity.Penjualan;
import com.mycompany.store_app.model.entity.User;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karis
 */
public class AdminMainPanel extends javax.swing.JPanel {

    private final BarangController bc;
    private final VoucherController vc;
    private final UserController uc;
    private final PenjualanController pc;
    /**
     * Creates new form BarangPanel
     */
    public AdminMainPanel() {
        initComponents();
        this.pc = new PenjualanController();
        this.vc = new VoucherController();
        this.bc = new BarangController();
        this.uc = new UserController();
        updateTableNota();
        updateTableUser();
        updateNumber();
    }
    
    public void updateNumber(){
        int member = uc.getAllData().size();
        int jumlahBarang = bc.ambilSemuaBarang().size();
        int jumlahVoucher = vc.ambilSemuaVoucer().size();
        List<Penjualan> listPenjualan = pc.getAll();
        
        double omset = 0;
        for (Penjualan penjualan : listPenjualan){
            omset += penjualan.getTotal();
        }
        
        txtMember.setText(String.valueOf(member));
        txtJumlahVoucer.setText(String.valueOf(jumlahVoucher));
        txtOmset.setText(String.valueOf(omset));
        txtJumlahBarang.setText(String.valueOf(jumlahBarang));
        
        
    }
    
    public void updateTableNota(){
        DefaultTableModel modelNota = (DefaultTableModel) tableNota.getModel();
        modelNota.setRowCount(0);
        List<Penjualan> listPenjualan = pc.getAll();
        int counter = 0;
        for (Penjualan penjualan : listPenjualan){
            Object[] rowData = {
                counter,
                penjualan.getId_nota(),
                penjualan.getTotal(),
                penjualan.getTanggal()
            
            };
            modelNota.addRow(rowData);
            counter++;
        }
    }
    public void updateTableUser(){
        DefaultTableModel modelUser = (DefaultTableModel) tableUser.getModel();
        modelUser.setRowCount(0);
        List<User> listUser = uc.getAllData();
        int counter = 0;
        for (User user : listUser){
            Object[] rowData = {
                counter,
                user.getNama(),
                user.getEmail() 
            };
            modelUser.addRow(rowData);
            counter++;
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Omset = new javax.swing.JLabel();
        txtMember = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Member = new javax.swing.JLabel();
        txtOmset = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtJumlahBarang = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtJumlahVoucer = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNota = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();

        setBackground(new java.awt.Color(245, 247, 251));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Dashboard");

        jPanel1.setBackground(new java.awt.Color(46, 204, 113));
        jPanel1.setPreferredSize(new java.awt.Dimension(254, 140));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Omset.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Omset.setForeground(new java.awt.Color(255, 255, 255));
        Omset.setText("Omset");
        jPanel1.add(Omset, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtMember.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        txtMember.setForeground(new java.awt.Color(255, 255, 255));
        txtMember.setText("1");
        jPanel1.add(txtMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 190, -1));

        jPanel2.setBackground(new java.awt.Color(155, 89, 182));
        jPanel2.setPreferredSize(new java.awt.Dimension(254, 140));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Member.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Member.setForeground(new java.awt.Color(255, 255, 255));
        Member.setText("Member");
        jPanel2.add(Member, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtOmset.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        txtOmset.setForeground(new java.awt.Color(255, 255, 255));
        txtOmset.setText("1");
        jPanel2.add(txtOmset, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 190, -1));

        jPanel3.setBackground(new java.awt.Color(74, 144, 226));
        jPanel3.setPreferredSize(new java.awt.Dimension(254, 140));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Jumlah Barang");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, -1));

        txtJumlahBarang.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        txtJumlahBarang.setForeground(new java.awt.Color(255, 255, 255));
        txtJumlahBarang.setText("1");
        jPanel3.add(txtJumlahBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 190, -1));

        jPanel4.setBackground(new java.awt.Color(255, 107, 107));
        jPanel4.setPreferredSize(new java.awt.Dimension(254, 140));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Jumlah Voucher");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtJumlahVoucer.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        txtJumlahVoucer.setForeground(new java.awt.Color(255, 255, 255));
        txtJumlahVoucer.setText("1");
        jPanel4.add(txtJumlahVoucer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 190, -1));

        tableNota.setBackground(new java.awt.Color(255, 255, 255));
        tableNota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Kode Nota", "Total", "Tanggal"
            }
        ));
        jScrollPane1.setViewportView(tableNota);
        if (tableNota.getColumnModel().getColumnCount() > 0) {
            tableNota.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        tableUser.setBackground(new java.awt.Color(255, 255, 255));
        tableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Username", "Email"
            }
        ));
        jScrollPane2.setViewportView(tableUser);
        if (tableUser.getColumnModel().getColumnCount() > 0) {
            tableUser.getColumnModel().getColumn(0).setMaxWidth(50);
            tableUser.getColumnModel().getColumn(1).setMinWidth(160);
            tableUser.getColumnModel().getColumn(1).setMaxWidth(160);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Member;
    private javax.swing.JLabel Omset;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tableNota;
    private javax.swing.JTable tableUser;
    private javax.swing.JLabel txtJumlahBarang;
    private javax.swing.JLabel txtJumlahVoucer;
    private javax.swing.JLabel txtMember;
    private javax.swing.JLabel txtOmset;
    // End of variables declaration//GEN-END:variables
}
