/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.store_app.view;
import com.mycompany.store_app.controller.BarangController;
import com.mycompany.store_app.model.entity.Barang;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karis
 */
public class BarangPanel extends javax.swing.JPanel {
    
    private final BarangController controller;

    /**
     * Creates new form BarangPanel
     */
    public BarangPanel() {
        initComponents();
        this.controller = new BarangController();
        updateTableBarang("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBarang = new javax.swing.JTable();
        btnTambahBarang = new javax.swing.JToggleButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(245, 247, 251));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Barang");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableBarang.setBackground(new java.awt.Color(255, 255, 255));
        tableBarang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tableBarang.setForeground(new java.awt.Color(51, 51, 51));
        tableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"3", "asu", "23000", "4"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nama", "Harga", "Stok"
            }
        ));
        tableBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBarang);
        if (tableBarang.getColumnModel().getColumnCount() > 0) {
            tableBarang.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 70, 1007, 569));

        btnTambahBarang.setBackground(new java.awt.Color(0, 255, 156));
        btnTambahBarang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTambahBarang.setForeground(new java.awt.Color(0, 0, 0));
        btnTambahBarang.setText("Tambah Barang ");
        btnTambahBarang.setBorderPainted(false);
        btnTambahBarang.addActionListener(this::btnTambahBarangActionPerformed);
        jPanel1.add(btnTambahBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 19, 210, 32));

        txtSearch.setBackground(new java.awt.Color(255, 255, 255));
        txtSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSearch.addActionListener(this::txtSearchActionPerformed);
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 19, 296, 32));

        btnSearch.setBackground(new java.awt.Color(0, 255, 156));
        btnSearch.setForeground(new java.awt.Color(0, 0, 0));
        btnSearch.setText("Search");
        btnSearch.setBorderPainted(false);
        btnSearch.addActionListener(this::btnSearchActionPerformed);
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(922, 19, 104, 33));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1046, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahBarangActionPerformed
        // TODO add your handling code here:
        
        InsertBarang panel = new InsertBarang(this);
        panel.setLocationRelativeTo(this);
        panel.setVisible(true);
        
    }//GEN-LAST:event_btnTambahBarangActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String keyword = txtSearch.getText().trim();
        updateTableBarang(keyword);
        
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tableBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBarangMouseClicked
        // TODO add your handling code here:
        
        int selectedRow = tableBarang.getSelectedRow();
        if (selectedRow != -1){
            int idBarang = Integer.parseInt(tableBarang.getValueAt(selectedRow, 0).toString());
            Barang barang = controller.ambilBarangById(idBarang);
            
            UpdateBarang panel = new UpdateBarang(this);
            panel.getData(barang);
            panel.setLocationRelativeTo(this);
            panel.setVisible(true);
        }
        
        
        
    }//GEN-LAST:event_tableBarangMouseClicked

    public void updateTableBarang(String keyword){
        if (keyword == null || keyword.isEmpty()){
            List<Barang> listBarang = controller.ambilSemuaBarang();
             
            DefaultTableModel modelBarang = (DefaultTableModel) tableBarang.getModel();
            modelBarang.setRowCount(0);
            
            for (Barang barang : listBarang){
                Object[] rowData = {
                    barang.getId(),
                    barang.getNama(),
                    barang.getHarga(),
                    barang.getStok()
                };
                modelBarang.addRow(rowData);
            }
        }else{
            List<Barang> listBarang = controller.searchByName(keyword);
             
            DefaultTableModel modelBarang = (DefaultTableModel) tableBarang.getModel();
            modelBarang.setRowCount(0);
            
            for (Barang barang : listBarang){
                Object[] rowData = {
                    barang.getId(),
                    barang.getNama(),
                    barang.getHarga(),
                    barang.getStok()
                };
                modelBarang.addRow(rowData);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JToggleButton btnTambahBarang;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableBarang;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
