/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.store_app.view;

import com.formdev.flatlaf.FlatClientProperties;

/**
 *
 * @author Flame
 */
public class MainPanel extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainPanel.class.getName());

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopPanel = new javax.swing.JPanel();
        CartButton = new javax.swing.JButton();
        CardMainPanel = new javax.swing.JPanel();
        ShoppingPanel = new javax.swing.JPanel();
        ShoppingTopPanel = new javax.swing.JPanel();
        FilterButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TopPanel.setBackground(new java.awt.Color(12, 185, 168));
        TopPanel.setPreferredSize(new java.awt.Dimension(1280, 65));
        TopPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CartButton.setBackground(new java.awt.Color(12, 185, 168));
        CartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shopping-cart.png"))); // NOI18N
        CartButton.setFocusPainted(false);
        CartButton.setFocusable(false);
        TopPanel.add(CartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1212, 12, 41, 41));
        CartButton.putClientProperty(FlatClientProperties.STYLE, "borderWidth: 0; focusColor: #0cb9a8");

        getContentPane().add(TopPanel, java.awt.BorderLayout.NORTH);

        CardMainPanel.setPreferredSize(new java.awt.Dimension(1280, 720));
        CardMainPanel.setLayout(new java.awt.CardLayout());

        ShoppingPanel.setBackground(new java.awt.Color(255, 255, 255));
        ShoppingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ShoppingTopPanel.setBackground(new java.awt.Color(255, 255, 255));
        ShoppingTopPanel.setPreferredSize(new java.awt.Dimension(1280, 50));
        ShoppingTopPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FilterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/filter.png"))); // NOI18N
        FilterButton.setMaximumSize(new java.awt.Dimension(55, 55));
        FilterButton.setMinimumSize(new java.awt.Dimension(55, 55));
        FilterButton.setPreferredSize(new java.awt.Dimension(35, 35));
        ShoppingTopPanel.add(FilterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 35, 35));
        FilterButton.putClientProperty(FlatClientProperties.STYLE, "borderWidth: 0");

        jTextField1.setText("jTextField1");
        ShoppingTopPanel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 720, 30));

        ShoppingPanel.add(ShoppingTopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        CardMainPanel.add(ShoppingPanel, "card2");

        getContentPane().add(CardMainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainPanel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardMainPanel;
    private javax.swing.JButton CartButton;
    private javax.swing.JButton FilterButton;
    private javax.swing.JPanel ShoppingPanel;
    private javax.swing.JPanel ShoppingTopPanel;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
