/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.store_app.view;

import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Cursor;
import javax.swing.*;

/**
 *
 * @author Flame
 */
public class PromptLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PromptLogin.class.getName());
    private String selectedform;
    
    private void enterSignUp(){
        SignInForm.setVisible(false);
        SignUpForm.setVisible(true);
    }
    
    private void enterSignIn(){
        SignInForm.setVisible(true);
        SignUpForm.setVisible(false);
    }
    /**
     * Creates new form PromptLogin
     */
    public PromptLogin() {
        initComponents();
        ((JComponent) getContentPane()).putClientProperty("FlatLaf.style", "background: #0cb9a8;");
        enterSignIn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SignInForm = new javax.swing.JPanel();
        UsernamePanel1 = new javax.swing.JPanel();
        UsernameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        SignInButton = new javax.swing.JButton();
        PasswordPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PasswordField1 = new javax.swing.JPasswordField();
        HeaderPanel1 = new javax.swing.JPanel();
        HeaderLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PromptPanel1 = new javax.swing.JPanel();
        SignUpLabel = new javax.swing.JLabel();
        LabelPrompt = new javax.swing.JLabel();
        SignUpForm = new javax.swing.JPanel();
        UsernamePanel = new javax.swing.JPanel();
        UsernameField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        SignUpButton = new javax.swing.JButton();
        PasswordPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        HeaderPanel = new javax.swing.JPanel();
        HeaderLabel1 = new javax.swing.JLabel();
        SubtextlLabel = new javax.swing.JLabel();
        PromptPanel = new javax.swing.JPanel();
        SignInLabel = new javax.swing.JLabel();
        LabelPrompt1 = new javax.swing.JLabel();
        EmailPanel = new javax.swing.JPanel();
        EmailField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ConfirmPasswordPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        ConfirmPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(12, 185, 168));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(16, 9));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        SignInForm.setBackground(new java.awt.Color(255, 255, 255));
        SignInForm.setPreferredSize(new java.awt.Dimension(450, 500));

        UsernamePanel1.setBackground(new java.awt.Color(255, 255, 255));

        UsernameField.addActionListener(this::UsernameFieldActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Username");

        javax.swing.GroupLayout UsernamePanel1Layout = new javax.swing.GroupLayout(UsernamePanel1);
        UsernamePanel1.setLayout(UsernamePanel1Layout);
        UsernamePanel1Layout.setHorizontalGroup(
            UsernamePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UsernameField)
            .addGroup(UsernamePanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UsernamePanel1Layout.setVerticalGroup(
            UsernamePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsernamePanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        SignInButton.setBackground(new java.awt.Color(11, 186, 81));
        SignInButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SignInButton.setForeground(new java.awt.Color(255, 255, 255));
        SignInButton.setText("Sign In");
        SignInButton.putClientProperty(FlatClientProperties.STYLE, "arc: 20");
        SignInButton.addActionListener(this::SignInButtonActionPerformed);

        PasswordPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Password");

        PasswordField1.addActionListener(this::PasswordField1ActionPerformed);

        javax.swing.GroupLayout PasswordPanel1Layout = new javax.swing.GroupLayout(PasswordPanel1);
        PasswordPanel1.setLayout(PasswordPanel1Layout);
        PasswordPanel1Layout.setHorizontalGroup(
            PasswordPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PasswordPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(PasswordField1)
        );
        PasswordPanel1Layout.setVerticalGroup(
            PasswordPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PasswordPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(PasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
        );

        HeaderPanel1.setBackground(new java.awt.Color(255, 255, 255));
        HeaderPanel1.setLayout(new java.awt.BorderLayout());

        HeaderLabel.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        HeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeaderLabel.setText("Welcome Back");
        HeaderPanel1.add(HeaderLabel, java.awt.BorderLayout.CENTER);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Sign in now to access");
        HeaderPanel1.add(jLabel4, java.awt.BorderLayout.PAGE_END);

        PromptPanel1.setOpaque(false);
        PromptPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignUpLabel.setForeground(new java.awt.Color(0, 0, 238));
        SignUpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignUpLabel.setText("Sign up");
        SignUpLabel.setPreferredSize(new java.awt.Dimension(40, 16));
        SignUpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignUpLabelMouseEntered(evt);
            }
        });
        PromptPanel1.add(SignUpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 0, -1, 25));

        LabelPrompt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelPrompt.setText("Don't have an account?");
        LabelPrompt.setMaximumSize(new java.awt.Dimension(202, 16));
        LabelPrompt.setPreferredSize(new java.awt.Dimension(202, 16));
        PromptPanel1.add(LabelPrompt, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 190, 25));

        javax.swing.GroupLayout SignInFormLayout = new javax.swing.GroupLayout(SignInForm);
        SignInForm.setLayout(SignInFormLayout);
        SignInFormLayout.setHorizontalGroup(
            SignInFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignInFormLayout.createSequentialGroup()
                .addGroup(SignInFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SignInFormLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(SignInFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PromptPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(PasswordPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SignInButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UsernamePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(SignInFormLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(HeaderPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SignInFormLayout.setVerticalGroup(
            SignInFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignInFormLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(HeaderPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(UsernamePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(PasswordPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(SignInButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PromptPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        SignInForm.putClientProperty(FlatClientProperties.STYLE, "arc: 20");

        getContentPane().add(SignInForm, new java.awt.GridBagConstraints());

        SignUpForm.setBackground(new java.awt.Color(255, 255, 255));
        SignUpForm.setPreferredSize(new java.awt.Dimension(450, 500));

        UsernamePanel.setBackground(new java.awt.Color(255, 255, 255));

        UsernameField1.addActionListener(this::UsernameField1ActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Username");

        javax.swing.GroupLayout UsernamePanelLayout = new javax.swing.GroupLayout(UsernamePanel);
        UsernamePanel.setLayout(UsernamePanelLayout);
        UsernamePanelLayout.setHorizontalGroup(
            UsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UsernameField1)
            .addGroup(UsernamePanelLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UsernamePanelLayout.setVerticalGroup(
            UsernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsernamePanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel5)
                .addGap(0, 0, 0)
                .addComponent(UsernameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        SignUpButton.setBackground(new java.awt.Color(11, 186, 81));
        SignUpButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SignUpButton.setForeground(new java.awt.Color(255, 255, 255));
        SignUpButton.setText("Sign Up");
        SignUpButton.putClientProperty(FlatClientProperties.STYLE, "arc: 20");

        PasswordPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Password");

        PasswordField.addActionListener(this::PasswordFieldActionPerformed);

        javax.swing.GroupLayout PasswordPanelLayout = new javax.swing.GroupLayout(PasswordPanel);
        PasswordPanel.setLayout(PasswordPanelLayout);
        PasswordPanelLayout.setHorizontalGroup(
            PasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PasswordPanelLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(PasswordField)
        );
        PasswordPanelLayout.setVerticalGroup(
            PasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PasswordPanelLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, 0)
                .addComponent(PasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
        );

        HeaderPanel.setBackground(new java.awt.Color(255, 255, 255));
        HeaderPanel.setLayout(new java.awt.BorderLayout());

        HeaderLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        HeaderLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeaderLabel1.setText("Welcome");
        HeaderPanel.add(HeaderLabel1, java.awt.BorderLayout.CENTER);

        SubtextlLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SubtextlLabel.setText("Sign up to get started");
        HeaderPanel.add(SubtextlLabel, java.awt.BorderLayout.PAGE_END);

        PromptPanel.setOpaque(false);
        PromptPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignInLabel.setForeground(new java.awt.Color(0, 0, 238));
        SignInLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignInLabel.setText("Sign in");
        SignInLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignInLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignInLabelMouseEntered(evt);
            }
        });
        PromptPanel.add(SignInLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 0, -1, 25));

        LabelPrompt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelPrompt1.setText("Already have an account?");
        LabelPrompt1.setMaximumSize(new java.awt.Dimension(202, 16));
        LabelPrompt1.setPreferredSize(new java.awt.Dimension(202, 16));
        PromptPanel.add(LabelPrompt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 190, 25));

        EmailPanel.setBackground(new java.awt.Color(255, 255, 255));

        EmailField3.addActionListener(this::EmailField3ActionPerformed);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Email");

        javax.swing.GroupLayout EmailPanelLayout = new javax.swing.GroupLayout(EmailPanel);
        EmailPanel.setLayout(EmailPanelLayout);
        EmailPanelLayout.setHorizontalGroup(
            EmailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmailField3)
            .addGroup(EmailPanelLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EmailPanelLayout.setVerticalGroup(
            EmailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmailPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel8)
                .addGap(0, 0, 0)
                .addComponent(EmailField3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ConfirmPasswordPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Confirm Password");

        ConfirmPasswordField.addActionListener(this::ConfirmPasswordFieldActionPerformed);

        javax.swing.GroupLayout ConfirmPasswordPanelLayout = new javax.swing.GroupLayout(ConfirmPasswordPanel);
        ConfirmPasswordPanel.setLayout(ConfirmPasswordPanelLayout);
        ConfirmPasswordPanelLayout.setHorizontalGroup(
            ConfirmPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmPasswordPanelLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(ConfirmPasswordField)
        );
        ConfirmPasswordPanelLayout.setVerticalGroup(
            ConfirmPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConfirmPasswordPanelLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, 0)
                .addComponent(ConfirmPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SignUpFormLayout = new javax.swing.GroupLayout(SignUpForm);
        SignUpForm.setLayout(SignUpFormLayout);
        SignUpFormLayout.setHorizontalGroup(
            SignUpFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpFormLayout.createSequentialGroup()
                .addGroup(SignUpFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SignUpFormLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(SignUpFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PromptPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(PasswordPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SignUpButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UsernamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ConfirmPasswordPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(SignUpFormLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SignUpFormLayout.setVerticalGroup(
            SignUpFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpFormLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(UsernamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(EmailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(PasswordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(ConfirmPasswordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(SignUpButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PromptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        SignUpForm.putClientProperty(FlatClientProperties.STYLE, "arc: 20");

        getContentPane().add(SignUpForm, new java.awt.GridBagConstraints());

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordField1ActionPerformed

    private void UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFieldActionPerformed

    private void SignUpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpLabelMouseClicked
        enterSignUp();
    }//GEN-LAST:event_SignUpLabelMouseClicked

    private void SignUpLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpLabelMouseEntered
        SignUpLabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_SignUpLabelMouseEntered

    private void UsernameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameField1ActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void SignInLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignInLabelMouseClicked
        enterSignIn();
    }//GEN-LAST:event_SignInLabelMouseClicked

    private void SignInLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignInLabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_SignInLabelMouseEntered

    private void EmailField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailField3ActionPerformed

    private void ConfirmPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmPasswordFieldActionPerformed

    private void SignInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInButtonActionPerformed

    }//GEN-LAST:event_SignInButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PromptLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmPasswordField;
    private javax.swing.JPanel ConfirmPasswordPanel;
    private javax.swing.JTextField EmailField1;
    private javax.swing.JTextField EmailField3;
    private javax.swing.JPanel EmailPanel;
    private javax.swing.JLabel HeaderLabel;
    private javax.swing.JLabel HeaderLabel1;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JPanel HeaderPanel1;
    private javax.swing.JLabel LabelPrompt;
    private javax.swing.JLabel LabelPrompt1;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JPasswordField PasswordField1;
    private javax.swing.JPanel PasswordPanel;
    private javax.swing.JPanel PasswordPanel1;
    private javax.swing.JPanel PromptPanel;
    private javax.swing.JPanel PromptPanel1;
    private javax.swing.JButton SignInButton;
    private javax.swing.JPanel SignInForm;
    private javax.swing.JLabel SignInLabel;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JPanel SignUpForm;
    private javax.swing.JLabel SignUpLabel;
    private javax.swing.JLabel SubtextlLabel;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JTextField UsernameField1;
    private javax.swing.JPanel UsernamePanel;
    private javax.swing.JPanel UsernamePanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
