/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.store_app.view;

import com.mycompany.store_app.controller.VoucherController;
import com.mycompany.store_app.model.entity.Voucher;
import static com.mycompany.store_app.view.MainPanel.addTextListener;
import java.awt.Color;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karis
 */
public class VoucherPanel extends javax.swing.JPanel {
    final private String SEARCHPLACEHOLDER = "Type to search for item...";
    private final VoucherController controller;
    private int EntryPerPage = 25;
    private int CurPage = 1;
    private int TotalPage;
    private double CurFilterHarga = 0;
    private List<Voucher> TableDataList = new ArrayList();
    /**
     * Creates new form VoucherPanel
     */
    public VoucherPanel() {
        initComponents();
        this.controller = new VoucherController();
        addTextListener(txtSearch, newtext -> {
            getTableData();
            loadPage();
        });
        getTableData();
        loadPage();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVoucher = new javax.swing.JTable();
        btnTambah = new javax.swing.JToggleButton();
        txtSearch = new javax.swing.JTextField();
        cbJenis = new javax.swing.JComboBox<>();
        NextButton = new javax.swing.JButton();
        PageNumberLabel = new javax.swing.JLabel();
        PreviousButton = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(245, 247, 251));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Voucher");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableVoucher.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tableVoucher.setForeground(new java.awt.Color(51, 51, 51));
        tableVoucher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Kode Voucher", "Jenis", "Diskon (...%)", "Stok"
            }
        ));
        tableVoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableVoucherMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableVoucher);
        if (tableVoucher.getColumnModel().getColumnCount() > 0) {
            tableVoucher.getColumnModel().getColumn(0).setPreferredWidth(50);
            tableVoucher.getColumnModel().getColumn(0).setMaxWidth(50);
            tableVoucher.getColumnModel().getColumn(2).setMinWidth(140);
            tableVoucher.getColumnModel().getColumn(2).setMaxWidth(140);
            tableVoucher.getColumnModel().getColumn(3).setMinWidth(130);
            tableVoucher.getColumnModel().getColumn(3).setMaxWidth(130);
            tableVoucher.getColumnModel().getColumn(4).setMinWidth(200);
            tableVoucher.getColumnModel().getColumn(4).setMaxWidth(200);
        }

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 70, 1007, 510));

        btnTambah.setBackground(new java.awt.Color(0, 255, 156));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTambah.setText("Tambah  Voucher");
        btnTambah.setBorderPainted(false);
        btnTambah.addActionListener(this::btnTambahActionPerformed);
        jPanel3.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 19, 210, 32));

        txtSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchFocusLost(evt);
            }
        });
        jPanel3.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 19, 400, 32));

        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "LIMITED", "PUBLIC", " " }));
        jPanel3.add(cbJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 130, 30));

        NextButton.setText("Next");
        NextButton.setPreferredSize(new java.awt.Dimension(100, 30));
        NextButton.addActionListener(this::NextButtonActionPerformed);
        jPanel3.add(NextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 600, -1, -1));

        PageNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PageNumberLabel.setText("0 / 0");
        jPanel3.add(PageNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 600, 100, 25));

        PreviousButton.setText("Previous");
        PreviousButton.setPreferredSize(new java.awt.Dimension(100, 30));
        PreviousButton.addActionListener(this::PreviousButtonActionPerformed);
        jPanel3.add(PreviousButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 600, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1046, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        
        InsertVoucher panel = new InsertVoucher(this, new InsertVoucher.InsertVoucherListener(){
            @Override
            public void onConfirmInsert() {
                getTableData();
                loadPage();
            }
        });
        panel.setLocationRelativeTo(this);
        panel.setVisible(true);
        getTableData();
        loadPage();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void tableVoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableVoucherMouseClicked
        // TODO add your handling code here:
        
        int selectedRow = tableVoucher.getSelectedRow();
        if (selectedRow != -1){
            int idVoucher = Integer.parseInt(tableVoucher.getValueAt(selectedRow, 0).toString());
            Voucher vcr = controller.getDataById(idVoucher);
            
            UpdateVoucher panel = new UpdateVoucher(this, new UpdateVoucher.UpdateVoucherListener() {
                @Override
                public void onConfirmUpdate() {
                    getTableData();
                    loadPage();
                }
            });
            panel.getData(vcr);
            panel.setLocationRelativeTo(this);
            panel.setVisible(true);
            getTableData();
            loadPage();
        }
        
    }//GEN-LAST:event_tableVoucherMouseClicked

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        if (CurPage < TotalPage) {
            CurPage ++;
        }
        getTableData();
        loadPage();
    }//GEN-LAST:event_NextButtonActionPerformed

    private void PreviousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousButtonActionPerformed
        if (1 < CurPage) {
            CurPage --;
        }
        getTableData();
        loadPage();
    }//GEN-LAST:event_PreviousButtonActionPerformed

    private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusGained
        txtSearch.setText("");
        txtSearch.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_txtSearchFocusGained

    private void txtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusLost
        if (txtSearch.getText().isBlank()){
            txtSearch.setForeground(new Color(153, 153, 153));
            txtSearch.setText(SEARCHPLACEHOLDER);
        }
    }//GEN-LAST:event_txtSearchFocusLost
    
    private String retrieveSearch(){
        if (txtSearch.getText().equals("Type to search for item...")){
            return "";
        } else {
            return txtSearch.getText();
        }
    }
        
    private void newRow(DefaultTableModel modelBarang, Voucher vc){
        DecimalFormat df = new DecimalFormat("#,##0.##");
        Object[] rowData = {
            vc.getId(),
            vc.getKode_voucher(),
            vc.getJenis_voucher(),
            vc.getDiskon(),
            vc.getStok()
        };
        modelBarang.addRow(rowData);
    }
    
    public void loadPage(){
        DefaultTableModel modelBarang = (DefaultTableModel) tableVoucher.getModel();
        modelBarang.setRowCount(0);
        
        for (Voucher vc : TableDataList){
            newRow(modelBarang, vc);
        }
    }
    
    public String getFilter(){
        return cbJenis.getSelectedItem().toString();
    }
    
    public void getTableData(){
        TotalPage = (int) Math.ceil((double) controller.count(getFilter(), retrieveSearch()) / EntryPerPage);
        System.out.println("com.mycompany.store_app.view.VoucherPanel.getTableData() " +TotalPage);
        if (TotalPage < CurPage) {
            CurPage = TotalPage;
            if (CurPage <= 0) {
                CurPage = 1;
            }
        }
        TableDataList = controller.ambilVoucherValid(EntryPerPage, CurPage, retrieveSearch(), "");
        PageNumberLabel.setText(CurPage + " / " + TotalPage);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NextButton;
    private javax.swing.JLabel PageNumberLabel;
    private javax.swing.JButton PreviousButton;
    private javax.swing.JToggleButton btnTambah;
    private javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableVoucher;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
